### ISSUE TITLE
I am unable to deploy on netlify

### ISSUE THREAD

**Issue by manadinho** [stablecog/stablecog#14]
I see following error.
An unhandled error in the function code triggered the following message:

Error - supabaseUrl is required.

Stack trace
Error: supabaseUrl is required.
    at new SupabaseClient (/var/task/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:55:19)
    at createClient (/var/task/node_modules/@supabase/supabase-js/dist/main/index.js:35:12)
    at createBrowserSupabaseClient (/var/task/node_modules/@supabase/auth-helpers-shared/dist/index.js:316:46)
    at createClient (file:///var/task/node_modules/@supabase/auth-helpers-sveltekit/dist/createClient.js:15:28)
    at file:///var/task/.netlify/server/chunks/supabase.js:3:18
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async Server.init (file:///var/task/.netlify/server/index.js:2641:22)
    at async Runtime.handler (file:///var/task/.netlify/serverless.js:295:4)

**Comment by bbedward** [comment]
Github issue is not the appropriate place for this, we'd like to keep this forum for actual bugs/feature requests/etc.

You're better off asking questions like this in our [discord](https://stablecog.com/discord), stablecog as-is has many dependencies (sc-worker, sc-go, supabase, redis, meili) - all of those need to be in place before you can configure and deploy the frontend to netlify.
